package com.syhbuy.spay.admin.dao;

import com.syhbuy.spay.admin.entity.Approve;
import org.apache.ibatis.annotations.Insert;

public interface ApproveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ROLE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_ADMIN_ROLE (ID, STATE, ",
        "NAME, ROLE_KEY, DESCRIPTION)",
        "values (#{id,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{roleKey,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})"
    })
    int insert(Approve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(Approve record);
}