package com.syhbuy.spay.admin.entity;

import java.util.List;

import javax.persistence.Transient;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;
    
    //新增属性与数据库无关
    @Transient
    private String sysTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    public void setId(String id) {
        this.id = id;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setCredentialsSalt(String credentialsSalt) {
        this.credentialsSalt = credentialsSalt;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setLocked(String locked) {
        this.locked = locked;
    }

   

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.CREDENTIALS_SALT
     *
     * @mbggenerated
     */
    private String credentialsSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.LOCKED
     *
     * @mbggenerated
     */
    private String locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_USER.DELETE_STATUS
     *
     * @mbggenerated
     */
    private String deleteStatus;

    private List<Role> roles;

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_USER
     *
     * @mbggenerated
     */
    public AdminUser(String id, String userName, String accountName, String password, String credentialsSalt, String description, String locked, Long createTime, String deleteStatus) {
        this.id = id;
        this.userName = userName;
        this.accountName = accountName;
        this.password = password;
        this.credentialsSalt = credentialsSalt;
        this.description = description;
        this.locked = locked;
        this.createTime = createTime;
        this.deleteStatus = deleteStatus;
    }
    public AdminUser(){

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.ID
     *
     * @return the value of T_ADMIN_USER.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.USER_NAME
     *
     * @return the value of T_ADMIN_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.ACCOUNT_NAME
     *
     * @return the value of T_ADMIN_USER.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.PASSWORD
     *
     * @return the value of T_ADMIN_USER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.CREDENTIALS_SALT
     *
     * @return the value of T_ADMIN_USER.CREDENTIALS_SALT
     *
     * @mbggenerated
     */
    public String getCredentialsSalt() {
        return credentialsSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.DESCRIPTION
     *
     * @return the value of T_ADMIN_USER.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.LOCKED
     *
     * @return the value of T_ADMIN_USER.LOCKED
     *
     * @mbggenerated
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.CREATE_TIME
     *
     * @return the value of T_ADMIN_USER.CREATE_TIME
     *
     * @mbggenerated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_USER.DELETE_STATUS
     *
     * @return the value of T_ADMIN_USER.DELETE_STATUS
     *
     * @mbggenerated
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

	/**
	 * 获取 createTime
	 * @return createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * 设置 createTime
	 * @param createTime createTime
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * 获取 sysTime
	 * @return sysTime
	 */
	public String getSysTime() {
		return sysTime;
	}

	/**
	 * 设置 sysTime
	 * @param sysTime sysTime
	 */
	public void setSysTime(String sysTime) {
		this.sysTime = sysTime;
	}
	
}