package com.syhbuy.spay.admin.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class Resources {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.ID
	 *
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.RES_NAME
	 *
	 * @mbggenerated
	 */
	private String resName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.PARENT_ID
	 *
	 * @mbggenerated
	 */
	private String parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.RES_KEY
	 *
	 * @mbggenerated
	 */
	private String resKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.TYPE
	 *
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.RES_URL
	 *
	 * @mbggenerated
	 */
	private String resUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.RES_LEVEL
	 *
	 * @mbggenerated
	 */
	private BigDecimal resLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.ICON
	 *
	 * @mbggenerated
	 */
	private String icon;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.IS_HIDE
	 *
	 * @mbggenerated
	 */
	private String isHide;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_ADMIN_RESOURCES.DESCRIPTION
	 *
	 * @mbggenerated
	 */
	private String description;

	private BigDecimal sort;

	private List<Role> roles ;

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public Resources(String id, String resName, String parentId, String resKey, String type, String resUrl, BigDecimal resLevel, String icon, String isHide, String description, BigDecimal sort) {
		this.id = id;
		this.resName = resName;
		this.parentId = parentId;
		this.resKey = resKey;
		this.type = type;
		this.resUrl = resUrl;
		this.resLevel = resLevel;
		this.icon = icon;
		this.isHide = isHide;
		this.description = description;
		this.sort = sort;
	}

	public BigDecimal getSort() {
		return sort;
	}

	public void setSort(BigDecimal sort) {
		this.sort = sort;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	private List<Resources> children = new ArrayList<Resources>();



	private List<Resources> nodes=new ArrayList<Resources>();

	public List<Resources> getNodes() {
		return nodes;
	}

	public void setNodes(List<Resources> nodes) {
		this.nodes = nodes;
	}

	public List<Resources> getChildren() {
		return children;
	}

	public void setChildren(List<Resources> children) {
		this.children = children;
	}



	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_ADMIN_RESOURCES
	 *
	 * @mbggenerated
	 */


	public Resources() {

	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.ID
	 *
	 * @return the value of T_ADMIN_RESOURCES.ID
	 *
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.RES_NAME
	 *
	 * @return the value of T_ADMIN_RESOURCES.RES_NAME
	 *
	 * @mbggenerated
	 */
	public String getResName() {
		return resName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.PARENT_ID
	 *
	 * @return the value of T_ADMIN_RESOURCES.PARENT_ID
	 *
	 * @mbggenerated
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.RES_KEY
	 *
	 * @return the value of T_ADMIN_RESOURCES.RES_KEY
	 *
	 * @mbggenerated
	 */
	public String getResKey() {
		return resKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.TYPE
	 *
	 * @return the value of T_ADMIN_RESOURCES.TYPE
	 *
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.RES_URL
	 *
	 * @return the value of T_ADMIN_RESOURCES.RES_URL
	 *
	 * @mbggenerated
	 */
	public String getResUrl() {
		return resUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.RES_LEVEL
	 *
	 * @return the value of T_ADMIN_RESOURCES.RES_LEVEL
	 *
	 * @mbggenerated
	 */
	public BigDecimal getResLevel() {
		return resLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.ICON
	 *
	 * @return the value of T_ADMIN_RESOURCES.ICON
	 *
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.IS_HIDE
	 *
	 * @return the value of T_ADMIN_RESOURCES.IS_HIDE
	 *
	 * @mbggenerated
	 */
	public String getIsHide() {
		return isHide;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_ADMIN_RESOURCES.DESCRIPTION
	 *
	 * @return the value of T_ADMIN_RESOURCES.DESCRIPTION
	 *
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public void setResKey(String resKey) {
		this.resKey = resKey;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setResUrl(String resUrl) {
		this.resUrl = resUrl;
	}

	public void setResLevel(BigDecimal resLevel) {
		this.resLevel = resLevel;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public void setIsHide(String isHide) {
		this.isHide = isHide;
	}
}