package com.syhbuy.spay.admin.dao;

import com.syhbuy.spay.admin.base.util.TreeNode;
import com.syhbuy.spay.admin.entity.AdminUser;
import com.syhbuy.spay.admin.entity.Resources;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_RESOURCES
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_ADMIN_RESOURCES (ID, RES_NAME, ",
        "PARENT_ID, RES_KEY, ",
        "TYPE, RES_URL, RES_LEVEL, ",
        "ICON, IS_HIDE, DESCRIPTION)",
        "values (#{id,jdbcType=VARCHAR}, #{resName,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=VARCHAR}, #{resKey,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{resUrl,jdbcType=VARCHAR}, #{resLevel,jdbcType=DECIMAL}, ",
        "#{icon,jdbcType=VARCHAR}, #{isHide,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})"
    })
    int insert(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_RESOURCES
     *
     * @mbggenerated
     */
    int insertSelective(Resources record);

    List<Resources> findResByUserId(String userId);

    List<Resources> findBtnByMenu(@Param("userId")String userId, @Param("parentId")String parentId);

    List<Resources> findPage(Resources resources);

    List<TreeNode> findResTreeByRoleId(String roleId,String parentId);

    int checkAuthorization(String roleId,String resId);

    int insertAuthorization(String roleId,String resId);

    void deleteResRole (Map<String, Object> params);

    List<Resources> selectResRole();
}