package com.syhbuy.spay.admin.dao;

import com.syhbuy.spay.admin.base.util.TreeNode;
import com.syhbuy.spay.admin.entity.AdminUser;
import com.syhbuy.spay.admin.entity.Role;
import org.apache.ibatis.annotations.Insert;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ROLE
     *
     * @mbggenerated
     */

    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ROLE
     *
     * @mbggenerated
     */

    int insertSelective(Role record);

    List<Role> findPage(Role role);

    List<TreeNode> getResById(String id);

    List<Role> findRoleAll();

    int insertUserRole(String userId,String roleId);
}